server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

client:
  url: http://loki:3100/api/prom/push

scrape_configs:
  - job_name: system
    pipeline_stages:
      - docker:
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          host: localhost
          __path__: /var/log/*.log

  - job_name: application
    pipeline_stages:
      - docker:
    static_configs:
      - targets:
          - localhost
        labels:
          job: application
          host: localhost
          __path__: /srv/log/app/*.json
