networks:
  logging:

volumes:
  loki:
  applicationLogs:

services:
  loki:
    image: grafana/loki:2.9.2
    container_name: "potato_loki"
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./config/loki/local-config.yaml:/etc/loki/local-config.yaml:ro
      - loki:/data
    user: root
    networks:
      - logging

  promtail:
    image: grafana/promtail:2.9.2
    container_name: "potato_promtail"
    depends_on:
      - loki
    volumes:
      - applicationLogs:/var/log/app
      - ./config/promtail/config.yaml:/etc/promtail/config.yml:ro
    command: -config.file=/etc/promtail/config.yml
    networks:
      - logging

  grafana:
    image: grafana/grafana:11.4.0
    container_name: "potato_grafana"
    depends_on:
      - loki
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    entrypoint:
      - sh
      - -euc
      - /run.sh
    ports:
      - "3000:3000"
    volumes:
      - ./config/grafana/ds.yaml:/etc/grafana/provisioning/datasources/ds.yaml:ro
    networks:
      - logging
